services:
    #Other service
    inventaire.stock.test.quantity: '@Labs\FacturationBundle\Services\StockTestQuantity'
    generate.reference.proforma: '@Labs\FacturationBundle\Services\generateRefProforma'
    get.montant.proforma: '@Labs\FacturationBundle\Services\getProformaMontant'
    rest_quantity: '@Labs\FacturationBundle\Twig\Extensions\QuantityOutRestExtension'

    #MemberBundle service
    user.redirect_registration_complet: '@Labs\MembersBundle\EventListener\RegistrationConfirmListener'
    access.user_login_route_listener: '@Labs\MembersBundle\EventListener\UserLoginRouteListener'
    nas_user.registration.form.type: '@Labs\MembersBundle\Form\Type\RegistrationFormType'
    nas_user.profile.edit.form.type: '@Labs\MembersBundle\Form\Type\ProfileFormType'